Repository canonical-web-and-design/docs.snapcraft.io, pull requests merged in 2019-04, with the labels that each got.

#132 Adds a branded search view
  README.md
  entrypoint
  package.json
  requirements.txt
  templates/base.html
  templates/search.html
  webapp/app.py
  webapp/models.py
  webapp/tests/test_models.py
Labels: Review: Code needed, Review: QA needed

#137 Replace discourse docs logic with module
  requirements.txt
  webapp/app.py
  webapp/models.py
  webapp/tests/fixtures/__init__.py
  webapp/tests/fixtures/snapcraft_forum_mock.py
  webapp/tests/test_models.py
Labels: Review: Code +1, Review: QA +1

#142 Reduce workers to 3
  entrypoint
Labels: Review: Code needed
